### ISSUE TITLE
Image being rendered ugly in pdf

### ISSUE THREAD

**Issue by bravemaster619** [floppylab/markdown2document#10]
JDK Version: 8u221
OS: Windows 10

```console
java -jar .\markdown2document-1.0.0.jar -mu "https://floppylab.com/resources/markdown2document/sample.md" -pf "sample.pdf"
```

**sample.pdf**

![image](https://user-images.githubusercontent.com/50212003/77257510-dd885f00-6caf-11ea-8a06-0f5d7e6866fe.png)

**Comment by leonorader** [comment]
@bravemaster619 by 'ugly' you mean? too big? or cut into pieces?

**Comment by bravemaster619** [comment]
I think the image should be automatically resized to fit the page width.
But your code has nothing to do with this. It's the dependency.

**Comment by leonorader** [comment]
I see. What about this solution as a nice feature, too:
The lib would provide a base.css, that is automatically included in the document, and if someone provides custom stylesheets, then the lib would use those?

**Comment by leonorader** [comment]
@bravemaster619 have you seen my previous comment? :)

**Comment by bravemaster619** [comment]
That would be cool. So this problem can be fixed with providing a custom css. Anyway, it's a sample and I think samples should work good without optional parameters other than specified in the document.

**Comment by leonorader** [comment]
Yes, it is a sample, but only the markdown sample, you did not use the sample css file.
I see your point, and yes using custom css will solve it anyway, but I think, this kind of base.css file would be a great improvement :) I will work on this :) Or would you like to assemble a simple base.css file? @bravemaster619

**Comment by bravemaster619** [comment]
@leonorader Thanks. I provided sample stylesheet and the pdf was rendered perfectly.

```console
java -jar .\markdown2document-1.0.0.jar -mu "https://floppylab.com/resources/markdown2document/sample.md" -pf "sample.pdf" -sl "https://floppylab.com/resources/markdown2document/sample.css"
```

I like the `base.css` idea. markdown files need that.
