### ISSUE TITLE
Content as a domain class

### ISSUE THREAD

**Issue by eurafa** [floppylab/markdown2document#16]
Hi, @leonorader ! How are you today?

It seems that `Content` has too much business code for a domain class.  
A classic domain class should not evolves I/O stuffs neither exception handling.  
I would suggest to consider using a pattern such as factory or builder.

Let me know what you think about it.

**Comment by leonorader** [comment]
Hi @eurafa :)

I agree. Absolutely. Would you like to refactor this, too perhaps? :)

**Comment by eurafa** [comment]
Yes. I love to refactor!! :D
I have some other ideas to refactor too.
You will see soon.

**Comment by leonorader** [comment]
sure, thanks again! :)

**Comment by leonorader** [comment]
Sorry, can I ask you to modify our little documentation, too? 
I mean in connection to the changes you've made :) @eurafa

**Comment by eurafa** [comment]
Of course. I will check it with attention.
But I remember that I kept `Content` constructor with `String` argument as default and basic usage.

**Comment by leonorader** [comment]
@eurafa Sure! But since `ContentFactory` exists, the documentation is not up to date, as it contains that Content object can be constructed from multiple sources, which is true, but the example code is not working :)
