### ISSUE TITLE
add default.css file

### ISSUE THREAD

**Issue by leonorader** [floppylab/markdown2document#17]
When the user does not provide any styles, use this `default.css` files to give the document a nice, simple and minimal design.

**Comment by bravemaster619** [comment]
I think the name `base.css` is kinda misleading. It should be a fallback option when styling options are missing. `default.css` is better. What do you think? :)

**Comment by leonorader** [comment]
Thanks @bravemaster619! :)

I agree that the name `default.css` would be better. :)

I checked your code, and I would not use the one on the floppylab site as it requires internet connection to work. I would simply put the `default.css` file in the codebase, maybe the `resources` folder :).

**Comment by leonorader** [comment]
Merged #19, closing issue, thanks @bravemaster619 again :)
