### ISSUE TITLE
Path.of or Paths.get? - Java version

### ISSUE THREAD

**Issue by bravemaster619** [floppylab/markdown2document#9]
## Java Version

I have built this project with jdk 8u221 and run some tests.
`Path.of` is introduced in Java 13 and does not work on Java 8.
I used `Paths.get` and worked good. However, `Paths.get` is deprecated.
So will this project support legacy Java 8 or follow newer versions?

**Comment by leonorader** [comment]
@bravemaster619 Oh yes, you are right. I used the wrong JDK all the time, sorry for that, and thanks for mentioning :)
I've got a PR, #11 from @yiding-he, thanks again! :)
